### ISSUE TITLE
Jump to entry without opening a preview window if it's the only one

### ISSUE THREAD

**Issue by kristijanhusak** [DNLHC/glance.nvim#1]
Hi,

Would you consider adding an option that would immediately jump to a location if it's a single entry in the preview window? I don't really need a preview in those cases so it's just to avoid a single jump.
Other than that, very nice and useful plugin. Will be replacing Telescope with it.

**Comment by DNLHC** [comment]
Hey,
That is a good point, i will consider adding an option to configure the behavior.

**Comment by DNLHC** [comment]
Examples on how to configure [before_open](https://github.com/DNLHC/glance.nvim#before_open) hook.

**Comment by kristijanhusak** [comment]
Works like a charm, thanks!
