### ISSUE TITLE
Highligh referenced name

### ISSUE THREAD

**Issue by D00mch** [DNLHC/glance.nvim#18]
It would be more convenient to see (with a highlight) what the reference is (on the left window) that you are looking (at the right window).

Example. On the screen below I don't know where is the `get-id` on the left window:
![image](https://user-images.githubusercontent.com/14236531/204231654-d7a6a97a-52df-4ccc-83a2-06e82c9a1112.png)

**Comment by D00mch** [comment]
My current workaround is to run a command like this to make it highlighted, at least:
```
mZ*`Z:Glance references<Cr>
```

**Comment by DNLHC** [comment]
Hi,
The referenced keyword in the preview should be highlighted with the `GlancePreviewMatch` group, which should have colors inherited from your `Search` hl group.
Could you check what colors it has `:hi GlancePreviewMatch`?
And your Search `:hi Search`

**Comment by D00mch** [comment]
Thank you for the reply.

```
:hi GlancePreviewMatch
GlancePreviewMatch xxx cleared.

:hi Search
Search xxx cterm=bold gui=bold guifg=#111827 guibg=#a5b4fc
```

I have only these mappings related to highlight:
```
set incsearch
set hlsearch
```

**Comment by DNLHC** [comment]
I did some testing with different colorschemes and found out that sometimes `glance` will fail to setup highlights properly.
Make sure to call the `require('glance').setup` after your colorscheme is installed
Also could you share the name of your colorsceme so i could test it with my setup?

**Comment by D00mch** [comment]
[tundra](https://github.com/sam4llis/nvim-tundra) and [nightfox](https://github.com/EdenEast/nightfox.nvim).

**Comment by DNLHC** [comment]
You can temporarily set the highlighting yourself, until i fix the issue
```lua
-- goes after require('glance').setup()
vim.api.nvim_set_hl(0, 'GlancePreviewMatch', { link = 'Search' })
```
or
```
hi! link GlancePreviewMatch Search
```

**Comment by D00mch** [comment]
Moving `setup` after setting theme didn't work. 

I also have an autocmd to clear highlights on colorscheme, but removing it also didn't help.

```fnl
(vim.api.nvim_create_autocmd
      :ColorScheme
      {:buffer   bufnr
       :group    (vim.api.nvim_create_augroup :HighlightColors {:clear true})
       :callback highlight-line-symbol})
```

Adding `vim.api.nvim_set_hl(0, 'GlancePreviewMatch', { link = 'Search' })` also didn't help.

P.S.
this one works :)
```
mZg*`Z:Glance references<Cr>
```
Everything with the name is highlighted.
