### ISSUE TITLE
Exposing preview's win_opts via config

### ISSUE THREAD

**Issue by ldelossa** [DNLHC/glance.nvim#21]
What are your thoughts on exposing the win_opts table in the preview module to the config?

My goal here is to set "wrap=false". 

Was seeing if I could do this from the hook, but I think all the window options are internal to preview.lua module.

**Comment by DNLHC** [comment]
You can't do that right now with the hook.
But yes, exposing the preview win options is in my plans

**Comment by ldelossa** [comment]
awesome :) I'll leave the "wrap = true" hack in my local copy for now.
