### ISSUE TITLE
Glance hangs around 10% of the time

### ISSUE THREAD

**Issue by marcomayer** [DNLHC/glance.nvim#24]
I updated glance today and noticed that on about 10% of the time it will cause nvim to hang (running with 100% CPU) calling `Glance references` for example.

 I did roll back to commit 1daea15c22145942361d0d911a6bff331d47b4ec now and it works totally fine again. I'm using the latest stable (0.8.1) on neovim.

**Comment by DNLHC** [comment]
Hi,
All the changes after that commit shouldn't really affect the performance, i cannot reproduce the issue.
Did you test the performance differences on the same code base? And what LSP client did you use when it started happening?

**Comment by marcomayer** [comment]
Thanks for your reply. I did pull master again today and now can't reproduce it anymore myself. Probably it was some unrelated issue and was just accidentally solved by restarting a few times.
