### ISSUE TITLE
Jumplists are no pushed to on file location jump

### ISSUE THREAD

**Issue by ldelossa** [DNLHC/glance.nvim#32]
If you jump to a file location using Glance.nvim, you'll notice that the jump locations before and after are not appended to the jumplist. You can see this with 'jumps' after using a file jump. 

This breaks 'ctrl-o' and 'ctrl-i`

**Comment by DNLHC** [comment]
Thanks. Should be working now.

**Comment by ldelossa** [comment]
working now. thanks!
