### ISSUE TITLE
actions.preview_scroll_win(-1) doesn't work reliably

### ISSUE THREAD

**Issue by marcomayer** [DNLHC/glance.nvim#33]
Having these mapping:
```
	mappings = {
			list = {
				["<C-d>"] = actions.preview_scroll_win(-5),
				["<C-e>"] = actions.preview_scroll_win(-1),
}}
```
When scrolling while focus is in list-view, Scrolling -1 using <C-e> doesn't always work. It works a couple of times but then stops and doesn't go further while scrolling -5 with <C-d> always does the job. Hope you can reproduce this, I'm on neovim 0.9 (99cf111289bfcd14981255e805da43bac5139141).

**Comment by DNLHC** [comment]
Thank you.
