### ISSUE TITLE
Show glance window above all buffers

### ISSUE THREAD

**Issue by elliotwesoff** [DNLHC/glance.nvim#36]
Hi there, currently when I open the glance window the width is restricted to the size of the calling buffer window. This is fine when I only have one buffer open, but is problematic when I have multiple vertical splits open. Is it possible to have it hover above all other buffers when opened? I tried setting `zindex = 100`, but that didn't help. Thanks!

**Comment by DNLHC** [comment]
Hey,
Currently it's impossible to expand glance beyond the active window. I've considered making the preview window adaptive, for example, when the active window is too small - render glance full screen wide. However this will greatly complicate the codebase. Glance was initially designed to work as an "embedded" window inside your buffer. With full screen width some features will not work properly.
I could add an option to toggle on/off the list window, that way the preview window will have the width of the active window. In glance it's possible to navigate the results inside the preview window with a keymap. What do you think?

**Comment by williamboman** [comment]
I'd like this as well as I tend to work on smaller screens (and rarely full screen). I found the following to work pretty well after somewhat limited testing:

```diff
diff --git a/lua/glance/config.lua b/lua/glance/config.lua
index f9f0572..2f11818 100644
--- a/lua/glance/config.lua
+++ b/lua/glance/config.lua
@@ -7,6 +7,7 @@ config.hl_ns = 'Glance'
 
 function config.setup(user_config, actions)
   local defaults = {
+    full_width = true,
     height = 18,
     zindex = 45,
     preview_win_opts = {
diff --git a/lua/glance/init.lua b/lua/glance/init.lua
index 6a199b1..766a943 100644
--- a/lua/glance/init.lua
+++ b/lua/glance/init.lua
@@ -53,19 +53,24 @@ local function get_preview_win_height(winnr)
 end
 
 local function get_win_opts(winnr, line)
-  local win_width = vim.fn.winwidth(winnr)
+  local full_width = config.options.full_width
+  local win_width = full_width and vim.o.columns or vim.fn.winwidth(winnr)
   local list_width = utils.round(
     win_width * math.min(0.5, math.max(0.1, config.options.list.width))
   )
   local preview_width = win_width - list_width
   local height = get_preview_win_height(winnr)
   local list_pos = config.options.list.position
+  local row = line
+  if full_width and vim.o.winbar ~= "" then
+    row = row + 1
+  end
   local win_opts = {
-    relative = 'win',
+    relative = full_width and 'editor' or 'win',
+    win = (not full_width) and winnr or nil,
     height = height,
-    win = winnr,
     zindex = config.options.zindex,
-    row = line,
+    row = row,
   }
 
   local list_win_opts = vim.tbl_extend('keep', {
```

**Comment by DNLHC** [comment]
I'll think about introducing an option to control the adaptability of the width,
The reason I'm hesitant is because my plan was to implement not just a float, but an embedded window to play well around your active buffer (with scrolling into view if necessary, rendering virtual lines underneath the active buffer, so your code flow is not abstracted by the preview, which is not yet implemented due to limitations in existing neovim API)

**Comment by elliotwesoff** [comment]
@DNLHC It's not difficult for me to reopen the file in a new tab and then call the glance functions. If it's too much trouble for you to add a floating window then no worries, I can use it as-is. I love your plugin! Great work!

**Comment by DNLHC** [comment]
The feature is done, apologies for the delay

Detached mode (render above all windows) can be configured with the new option `detached`
By default glance will enable detached mode when the active window is smaller than 100 columns, check the documentation for examples

@williamboman thanks for the reference code!

**Comment by elliotwesoff** [comment]
Dude this is awesome!!! Thank you!!!!!
