### ISSUE TITLE
Feature Request: support many more lsp operations?

### ISSUE THREAD

**Issue by linrongbin16** [DNLHC/glance.nvim#41]
Hi, is there a plan to support more operations?
Declaration, incoming calls, outgoing calls, code actions, in the same style.
Even diagnostics, hover, signature help, since I really love this style.

**Comment by linrongbin16** [comment]
Since lsp method declarations method shares the same response with definitions, I submit #42 to add it.

**Comment by DNLHC** [comment]
Hi,
yes, call hierarchy will be supported at some point
diagnostics, hover, signature help, etc. i'm afraid out of scope for this plugin, Glance is a peek preview window.

**Comment by DNLHC** [comment]
I will close this in favor for https://github.com/DNLHC/glance.nvim/issues/29

**Comment by linrongbin16** [comment]
Hi, it is a matter of taste about what lsp method should be handled. it's your project, it's your call.
