### ISSUE TITLE
Cannot change config in setup block

### ISSUE THREAD

**Issue by c02y** [DNLHC/glance.nvim#44]
Unable to change any filed in setup block, none of my changes works.

I'm using LunarVim if it matters.

![image](https://user-images.githubusercontent.com/2135996/226221879-2c31a939-5a8e-4977-8ab4-b7d76acd683e.png)

**Comment by DNLHC** [comment]
Hey,
Could you try disabling the theme setting?
```lua
theme = {
  enabled = false
}
```
This feature doesn't work well with some themes.
What version of nvim are you running?

**Comment by c02y** [comment]
Already did, from the first beginning, actually I tried to change the background color of the pop window since it is same with the terminal, so I tried to change the theme or border, then I found none of the configs works.

```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by c02y** [comment]
**UPDATE**:

Sorry about that, it seems it is Packer issue, I have to run `PackerCompile` after I edit my config file.

Changing border or list config is working now.
But it
```
theme = {
  enabled = false
}
```
still doesn't work

BTW: I'm using the default theme.

**Comment by DNLHC** [comment]
Yeah, it should be `enable = false` without the `d` at the end, sorry my bad

**Comment by c02y** [comment]
> Yeah, it should be `enable = false` without the `d` at the end, sorry my bad

it's ok, I'm using `enable` in my config, you can see that in the screenshot.

**Comment by DNLHC** [comment]
Are you sure the theme is not disabled? Try executing `:hi GlanceListNormal` command, it should say the highlight is cleared.

**Comment by c02y** [comment]
yes：
![image](https://user-images.githubusercontent.com/2135996/226499634-4582ff01-fe9f-4c46-9ecc-e63af965ea80.png)

**Comment by DNLHC** [comment]
It is disabled then. Since your colorscheme lacks the required highlights for glance to borrow you'll have to highlight it yourself. You can check the defined highlight groups [here](https://github.com/DNLHC/glance.nvim#highlights)

**Comment by c02y** [comment]
Thanks.
