### ISSUE TITLE
Bug: When closing Glance, jumps to the end of the buffer

### ISSUE THREAD

**Issue by chrisgrieser** [DNLHC/glance.nvim#45]
When I close the Glance window without opening an item (i.e, `q` or `esc`), then the cursor jumps to the last line in the buffer, as if I had pressed `G`.

It seems my jump history is somewhat messed up by Glance: when I do jump to a definition/reference, jumping back leads me to the last line of the buffer as well instead of jumping to the actual location I opened glance from.

---

A far from ideal workaround I use for now:
```lua
hooks = {
	before_open = function(results, open, _)
		vim.cmd.mkview(3)
		open(results)
	end,
	after_close = function()
		local isOnLastLine = vim.fn.line(".") == vim.fn.line("$")
		if isOnLastLine then vim.cmd.loadview(3) end
	end,
},
```

**Comment by DNLHC** [comment]
Hey,
Do you by any chance run glance full height? How big is the preview compared to the active window?
This bug happens when the preview is too big, try decreasing the height.

**Comment by chrisgrieser** [comment]
Hi,

my window has a height of 29, and I set Glance to a height of 20

**Comment by DNLHC** [comment]
This could also happen when you have high `scrolloff` value configured

**Comment by chrisgrieser** [comment]
oh yes, indeed I do have a relatively high scrolloff value, namely 15.

**Comment by chrisgrieser** [comment]
okay, reducing the height to 12 indeed fixes the issue, even though it is a bit small...

So I tried changing the scrolloff, and this workaround to change the scrolloff before entering glance and restoring it after leaving glance seems to work. Maybe this could be added the glance?

```lua
hooks = {
	before_open = function(results, open, _)
		vim.opt_local.scrolloff = 0
		open(results)
	end,
	after_close = function()
		vim.opt_local.scrolloff = vim.opt_global.scrolloff:get()
	end,
},
```

**Comment by chrisgrieser** [comment]
great, thanks for the quick fix 😊

**Comment by DNLHC** [comment]
Should be fixed now, thanks for reporting!
