### ISSUE TITLE
FR: Support for Live Grep

### ISSUE THREAD

**Issue by chrisgrieser** [DNLHC/glance.nvim#49]
I found the ability to quickly edit files by switching to the preview window to be so helpful, that I kinda wish that this would also work for live-grep results. I can see though that live grep will be a bit tricker to implement, since it would require dealing with a dynamically changed search term.

Nevertheless, thank you for this incredibly useful plugin.

**Comment by DNLHC** [comment]
Making glance a more universal tool is a cool idea, but that will bring a lot of breaking changes and will require a rewrite.
I'd prefer to keep the plugin simple and focus on one thing - LSP, sorry.
Maybe in the future I'll think about it.

**Comment by chrisgrieser** [comment]
Sure, no problem, I can understand that!
