### ISSUE TITLE
"Glances" is obstructed by backgrounds highlights

### ISSUE THREAD

**Issue by wroyca** [DNLHC/glance.nvim#53]
Setting some background highlight will visually override glances:

E.g. LineNrAbove, LineNrBelow, DiagnosticSignError, DiagnosticSignWarn, DiagnosticSignInfo, DiagnosticSignHint - ? 

![image](https://github.com/DNLHC/glance.nvim/assets/91024200/b278729b-dac9-46dd-8002-d1839403d56e)
![image](https://github.com/DNLHC/glance.nvim/assets/91024200/decb4679-ec46-4ef1-94ea-b63696e2922b)

**Comment by DNLHC** [comment]
Can you give more details about the screenshots and steps to reproduce the problem?

**Comment by wroyca** [comment]
> Can you give more details about the screenshots and steps to reproduce the problem?

In essence, when we open Glance preview, we anticipate that the "dimming" effect would also be applied to `SignColumn` and `LineNr`, and indeed it is. However, if we set the background color for these two, it results in overlapping colors, as shown in the second screenshot. 

To recreate the issue:

 * Open Glance preview window.
 * Within Nvim, use `highlight LineNrAbove guibg=red` to set LineNrAbove background color.

![image](https://github.com/DNLHC/glance.nvim/assets/91024200/90218c4e-1c43-4d3c-97d4-3419fe1121c9)

Repeat the procedure, with, say, diagnostics, signcolumn, LineNr, LineNrBelow, etc.
