### ISSUE TITLE
File Icons

### ISSUE THREAD

**Issue by doganalper** [DNLHC/glance.nvim#54]
File icons seems to be rendering wrong.
<img width="485" alt="image" src="https://github.com/DNLHC/glance.nvim/assets/48688801/7a760e76-4705-441c-8869-0552fd50c07d">

**Comment by DNLHC** [comment]
These are not file icons but arrows indicating fold state. If your font doesn't support these characters you can configure fold icons yourself:
```lua
glance.setup({
  folds = {
    fold_closed = '>',
    fold_open = 'v',
  },
})
```

**Comment by DNLHC** [comment]
I updated fold characters, by default nerdfont icons are used.

**Comment by doganalper** [comment]
I still renders same even after updating, my font is JetBrains Nerd Font Mono. Updated with config you have given me, it works correctly.
