### ISSUE TITLE
Split to right/below

### ISSUE THREAD

**Issue by ryoppippi** [DNLHC/glance.nvim#63]
Hi!
Thank you for creating this fantastic plugin.

So, is there any split to right/ split to bottom actions when I jump to the definition

**Comment by DNLHC** [comment]
Hey
Yes, there are actions for that: `jump_vsplit`, `jump_split`
These are the default keymaps, but you can change them if you need.
```lua
local glance = require('glance')
local actions = glance.actions

glance.setup({
  mappings = {
    list = {
      ['v'] = actions.jump_vsplit,
      ['s'] = actions.jump_split,
    }
})
```

**Comment by ryoppippi** [comment]
Thank you but
When I use `jump_vsplit` the new windows is created on left side.
How can I make the new window to the right??

**Comment by DNLHC** [comment]
Direction of a splitting window in neovim is configured globally with these settings
```lua
vim.opt.splitright = true
vim.opt.splitbelow = true
```

**Comment by ryoppippi** [comment]
Ok it works! thanks
