### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by Bekaboo** [DNLHC/glance.nvim#66]
I am looking forward to the support of other LSP actions that needs a preview window, e.g. incoming/outgoing calls, declarations, etc. as mentioned in https://github.com/DNLHC/glance.nvim/issues/41 and https://github.com/DNLHC/glance.nvim/issues/29, but seems that there's no code contributed for these features in one year.

So I wonder what is the current state of this project. Is it in a maintenance state and stops implementing new features?

Thanks in advance.

**Comment by pidgeon777** [comment]
I'm also wondering this

**Comment by weilbith** [comment]
Open a PR? Or make a solution approach proposal? 🤔

**Comment by DNLHC** [comment]
Hey, apologies for not responding sooner.

`CallHierarchy` is not the priority right now, it will most likely require a major rewrite of list navigation code. I will look into it more closely next week.
