### ISSUE TITLE
“Attempt to index local 'hooks' (a nil value)”

### ISSUE THREAD

**Issue by michenriksen** [DNLHC/glance.nvim#8]
Hi there, thanks for your work on this plugin, it looks like an excellent addition to my setup!

I am unfortunately experiencing a problem in my AstroNvim setup when trying to invoke `:Glance references` -- I get the following error message and stack trace:

```
Error executing vim.schedule lua callback: ...m/site/pack/packer/start/glance.nvim/lua/glance/init.lua:136: attempt to index local 'hooks' (a nil value)
stack traceback:
        ...m/site/pack/packer/start/glance.nvim/lua/glance/init.lua:136: in function 'handler'
        ...im/site/pack/packer/start/glance.nvim/lua/glance/lsp.lua:31: in function 'handler'
        ...w/Cellar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

It seems like the `hooks` map is always `nil` for some reason. This is my Packer init:

```lua
...

"dnlhc/glance.nvim",
config = function()
  require("glance").setup({})
end,

...

}
```

So, it should be set up with the default options which should have `{}` as default for its hooks, but it somehow gets converted into a nil value.

I also tried to configure it like:

```lua
require("glance").setup({
  hooks = {
    "before_open" = function(results, open, jump, method)
      open(results)
    end,
  },
})
```

But I still receive the same error message when running `:Glance references`

I'll continue with my debugging, but any help would be greatly appreciated! 🙇

**Comment by DNLHC** [comment]
Hey, thanks for reporting.
That's very strange and shouldn't happen, i cannot reproduce the issue with my setup.
Can you try to reinstall the plugin?

**Comment by michenriksen** [comment]
I made it work after running `:PackerSync` 🤷 

Amazing plugin, thanks again!
